### ISSUE TITLE
Train Model.

### ISSUE THREAD

**Issue by rawatshubham09** [rawatshubham09/Sign_Language_Detector#4]
# Task for Todays work
- [x] Clone Yolo git repo
- [x] Chose suitable model according your need
- [x] Change no. of object and file location
- [ ] Train the model
- [ ] Test and Upload to git

**Comment by rawatshubham09** [comment]
Few thing done there is some issue in my code
